
version: '3.8'

services:
  go-app:
    image: vksssd/go-app:latest
    # image: go-app
    ports:
      - "8080:8080"
    platform: linux/amd64
    
  node-app:
    image: vksssd/node-app:latest
    # image: node-app
    ports:
      - "3000:3000"
    platform: linux/amd64


  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30  # Check for updates every 30 seconds