version: 2.1

jobs:
  build-go:
    docker:
      - image: circleci/golang:1.16
      # - image: circleci/node:14

    steps:
      - checkout

      # Go application build and test
      - run:
          name: Build and test Go application
          command: |
            cd go-app
            go build -o app
            go test ./...
      
      # Docker login to Docker Hub
      # - run:
      #     name: Docker login
      #     command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build and push Docker images to Docker Hub
      - run:
          name: Build and push Docker images
          command: |
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            cd go-app
            docker build -t vksssd/go-app:latest .
            docker push vksssd/go-app:$TAG
            docker tag vksssd/go-app:$TAG vksssd/go-app:latest
            docker push vksssd/go-app:latest

      # # Node.js application build and test
      # - run:
      #     name: Build and test Node.js application
      #     command: |
      #       cd nodejs-app
      #       npm install
      #       npm test


  build-node:
    docker:
      - image: circleci/node:14

    steps:
        - checkout

        - run:
            name: Build and test Node.js application
            command: |
              cd node-app
              npm install
              npm test

        # -  run:
        #     name: Docker login
        #     command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build and push Docker images to Docker Hub
        -  run:
            name: Build and push Docker images
            command: |
              TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              cd node-app
              docker build -t vksssd/node-app:latest .
              docker push vksssd/node-app:$TAG
              docker tag vksssd/node-app:$TAG vksssd/node-app:latest
              docker push vksssd/node-app:latest


workflows:
  version: 2
  build:
    jobs:
      - build-go
      - build-node

