version: 2.1

executors:
  docker-go-executor:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/vksssd/go-node-devops

  docker-node-executor:
    docker:
      - image: circleci/node:14
    working_directory: /node/src/github.com/vksssd/go-node-devops

jobs:
  build-go:
    executor: docker-go-executor
    steps:
      - checkout

      - run:
          name: Build Docker image for Go application
          command: docker build -t go-app -f go-app/Dockerfile .
      
      - run:
          name: Build and test Go application
          command: |
            pwd 
            cd go-app
            go mod tidy
            go build -o app
            go test ./...
      
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build and push Docker images
          command: |
            cd go-app
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            docker build -t vksssd/go-app:latest .
            docker push vksssd/go-app:latest
            docker tag vksssd/go-app:latest vksssd/go-app:$TAG
            docker push vksssd/go-app:$TAG

  build-node:
    executor: docker-node-executor
    steps:
      - checkout

      - run:
          name: Build Docker image for Node.js application
          command: docker build -t node-app -f node-app/Dockerfile .

      - run:
          name: Build and test Node.js application
          command: |
            cd node-app
            npm install
            npm test

      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Docker login
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build and push Docker images
          command: |
            cd node-app
            TAG=$(echo $CIRCLE_SHA1 | cut -c1-7)
            docker build -t vksssd/node-app:latest .
            docker push vksssd/node-app:latest
            docker tag vksssd/node-app:latest vksssd/node-app:$TAG
            docker push vksssd/node-app:$TAG

workflows:
  version: 2
  build:
    jobs:
      - build-go
      - build-node
